// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type DhExpertClass struct {
	ent.Schema
}

func (DhExpertClass) Fields() []ent.Field {
	return []ent.Field{
		field.Uint64("id").Unique(),
		field.String("name").Comment("专家类型"),
	}
}
func (DhExpertClass) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("expert_class",DhExpert.Type).Ref("class_relation"),
	}
}
func (DhExpertClass) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "dh_expert_class"}}
}
