# docker-compose --env-file=.env up -d
version: "3"
# 通用配置
x-common-config: &common-config
  KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  KAFKA_NUM_PARTITIONS: 3
  KAFKA_DEFAULT_REPLICATION_FACTOR: 2

# kafka镜像通用配置
x-kafka: &kafka
  image: wurstmeister/kafka
  networks:
    net:
  depends_on:
    - zookeeper

services:

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - net
    volumes:
      - zookeeper_data:/wurstmeister/zookeeper

  kafka-0:
    container_name: kafka-0
    <<: *kafka
    ports:
      - "9093:9093"
    environment:
      <<: *common-config
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.10.190:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
    volumes:
      - kafka_0_data:/wurstmeister/kafka

  kafka-1:
    container_name: kafka-1
    <<: *kafka
    ports:
      - "9094:9094"
    environment:
      <<: *common-config
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.10.190:9094
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094
    volumes:
      - kafka_1_data:/wurstmeister/kafka

  kafka-2:
    container_name: kafka-2
    <<: *kafka
    ports:
      - "9095:9095"
    environment:
      <<: *common-config
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.10.190:9095
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9095
    volumes:
      - kafka_2_data:/wurstmeister/kafka

volumes:
  zookeeper_data:
  kafka_0_data:
  kafka_1_data:
  kafka_2_data: 


networks:
  net:
    driver: bridge

