# FROM golang:1.20 AS builder

# COPY . /src
# WORKDIR /src

# RUN go mod tidy && GOPROXY=https://goproxy.cn go build -o server main.go

# GOOS=linux GOARCH=amd64 go build -o main main.go

#docker build -t gin:demo . 

# docker run  -it -p 8085:8085 gin:demo
FROM debian:stable-slim

# COPY --from=builder /src/bin /app

COPY ./main /app/

WORKDIR /app

EXPOSE 8085

CMD ["./main"]